services:
  # 1. Dịch vụ lưu trữ metadata cho Milvus
  etcd:
    container_name: milvus-etcd-standalone
    image: quay.io/coreos/etcd:v3.5.14
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  # 2. Dịch vụ lưu trữ file (object storage) cho Milvus
  minio:
    container_name: milvus-minio-standalone
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001" # Port cho giao diện Web UI của Minio
      - "9000:9000" # Port cho API
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "mc ready local"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. Dịch vụ Milvus Standalone chính
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.23
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/milvus/data
    ports:
      - "19530:19530" # Port gRPC cho Python client
      - "9091:9091" # Port HTTP
    depends_on:
      # Đảm bảo etcd và minio khởi động trước Milvus
      - "etcd"
      - "minio"

  # 4. Dịch vụ Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.8
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 5. UI cho Milvus (Attu)
  attu:
    container_name: milvus-attu
    image: zilliz/attu:v2.2.8
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8001:3000" #
    depends_on:
      - "milvus"

  # 6. UI cho Elasticsearch (Kibana)
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.8 # Phải cùng phiên bản với Elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]' # Kết nối tới service 'elasticsearch'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch # Đảm bảo Elasticsearch khởi động trước Kibana

volumes:
  etcd_data:
  minio_data:
  milvus_data:
  es_data:
